Feat/chart pr
illa-family/illa-builder pull request #206
Opened 2022-07-13 07:28 UTC by Z-AOAO

## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

2022-07-13 07:56 UTC, zch-modier commented on src/page/App/components/PanelSetters/ChartSetter/DatasetsSetter/header.tsx
> +        <span>New</span>
这里要多语言吗

2022-07-13 08:21 UTC, zch-modier commented on src/widgetLibrary/Chart/panelConfig.tsx
> +  // {
没用的删掉吧

2022-07-13 08:21 UTC, zch-modier approved these changes

2022-07-14 02:21 UTC, AruSeito requested changes

2022-07-14 02:21 UTC, AruSeito commented on src/page/App/components/PanelSetters/ChartSetter/DatasetsSetter/colorSetter.tsx
> +          prefabricatedColors={COLOR_SCHEME.map((item) => ({
别在这个地方写 map，提到组件外部去

2022-07-14 02:21 UTC, AruSeito commented on src/page/App/components/PanelSetters/ChartSetter/chartDataSetter.tsx
> +          options={[
提到函数外面，定义成常量

2022-07-14 02:21 UTC, AruSeito commented on src/page/App/components/PanelSetters/ChartSetter/chartDataSetter.tsx
> +      {panelConfig?.["type"] !== "pie" && (
panelConfig?.type

2022-07-14 02:21 UTC, AruSeito commented on src/page/App/components/PanelSetters/ChartSetter/chartDataSetter.tsx
> +              handleUpdateDsl("groupBy", value)
函数提出去一下，callBack 一手

2022-07-14 02:21 UTC, AruSeito commented on src/page/App/components/PanelSetters/ChartSetter/removeDatasetButton.tsx
> +        width: 100%;
css 扔到 style 里去

2022-07-14 02:21 UTC, AruSeito commented on src/page/App/components/PanelSetters/ChartSetter/removeDatasetButton.tsx
> +        const _attrName = _attrNameArr[0]
提一下

2022-07-14 02:21 UTC, AruSeito commented on src/page/App/components/PanelSetters/ChartSetter/removeDatasetButton.tsx
> +          handleUpdateDsl(_attrName, [])
接一下 parentAttrName，直接用lodash 的 get(panelConfig,parentAttrName)

2022-07-14 02:21 UTC, AruSeito commented on src/widgetLibrary/Chart/chart.tsx
> +export const ChartWidget = WrappedChart
useEffect 搞一下，把 props 都挂到 globalData 上，看一下 text 的处理方式。transform 类的都丢到这里来处理，wrappedChart 只接受处理好的最终值。

2022-07-14 02:21 UTC, AruSeito commented on src/widgetLibrary/Chart/chart.tsx
> +    console.log("_datasets", res)
删一下

2022-07-14 02:21 UTC, AruSeito commented on src/widgetLibrary/Chart/tests/chart.test.tsx
> +  render(<div>Chart</div>)
test 直接删掉吧。等后面补的时候在写上，现在这样不太合理

2022-07-14 11:19 UTC, AruSeito approved these changes

2022-07-14 11:48 UTC, merged